### ISSUE TITLE
first load ws error

### ISSUE THREAD

**Issue by Gamer1990** [5ony/OBSWebSocketAHK#1]
newer to ahk got it set but there seems to be a Ws error(Line 45) unknown name and maybe a js error line:1 Char 1 syntaxError (As it remind me of that type of popup) looking forward to automating my Stream with this

**Comment by 5ony** [comment]
I think the problem might be that the websocket server is not running; it should be running already when starting the AHK script.
Or, if it is running already, it might be that AHK had no time to connect yet, still in connecting phase, but a command is sent to the websocket.

So, for example if you do something like this:

```
obsc := new MyOBSController("ws://192.168.1.100:4455/", 0, MyOBSController.EventSubscription.Input)
obsc.SetInputMute("Mic/Aux", obsc.Boolean(!obsc.muted))

```
then obsc.SetInputMute will cause an error, as the connection has not been established. The easiest/laziest way to handle this is with a delay, but the best way is to wait for the initialization phase and do your obs commands in AfterIdentified(). Check the example code in: example-toggle-a-scene-element.ahk

Let me know how it goes, and if you still have a problem, please add the code you are trying to run so I can test it myself as well.

Note to myself: the error is not too verbose, I might want to expand those error messages in the future.

**Comment by Gamer1990** [comment]
i think the ws issues is related to the
json error: line 1 char 1 syntax error

**Comment by 5ony** [comment]
Can you show me your code please?

I've tried to run example-toggle-a-scene.ahk , and it works fine. The problem happens only when it cannot join to OBS websocket server: IP address is not correct, authentication is set in OBS, but not in the script or OBS websocket is not enabled.

**Comment by Gamer1990** [comment]
#Include C:\Program Files\AutoHotkey\lib\OBSWebSocket.AHK
obsws := new OBSWebSocket("ws:192.168.11.244:4445/")return
Numpad1::obsws.SetCurrentProgramScene("4 Right")Return
Numpad2::obsws.SetCurrentProgramScene("Break")return
there a new error where as line 45: ws is not Named 
    On Friday, November 11, 2022 at 07:32:49 AM MST, 5ony ***@***.***> wrote:  
 
 


Can you show me your code please?

I've tried to run example-toggle-a-scene.ahk , and it works fine. The problem happens only when it cannot join to OBS websocket server: IP address is not correct, authentication is set in OBS, but not in the script or OBS websocket is not enabled.

**Comment by 5ony** [comment]
It seems that the websocket address is not correct (note the "ws://")
this
new OBSWebSocket("ws:192.168.11.244:4445/")
should be
new OBSWebSocket("ws://192.168.11.244:4445/")

**Comment by Gamer1990** [comment]
Do u have any Video on this scripting

**Comment by 5ony** [comment]
No video, sorry. If the documentation is not enough, I can help you on discord (my tag is Sony#1154) if you wish.
