### ISSUE TITLE
"SetInputVolume" request not working

### ISSUE THREAD

**Issue by Osmagtor** [5ony/OBSWebSocketAHK#11]
After upgrading to the latest release, the "SetInputVolume" request appears to have ceased working. Maybe it is completely unrelated to the latest release itself, but it was after updating that I first noticed it.

```
#Requires AutoHotkey v2.0

#Include OBSWebSocket.ahk

obsws := OBSWebSocket("ws://127.0.0.1:4455/", 0)

; Using "inputVolumeMul"

F12:: {
    obsws.SetInputVolume("Elgato HD", 15)
}

F11:: {
    obsws.SetInputVolume("Elgato HD", 5)
}

; ; Using "inputVolumeDb"

F9:: {
    obsws.SetInputVolume("Elgato HD", , 5)
}

F8:: {
    obsws.SetInputVolume("Elgato HD", , -20)
}
```

**Comment by 5ony** [comment]
@Osmagtor, thank you for reporting, you are right, sorry for this bug.
Fixed it in v2.0.6, let me know if it works with the newest version.

**Comment by Osmagtor** [comment]
While I'm at it, I've also noticed that the "GetProfileList" request expects some parameters as part of the request when they are part of the [response ](https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#getprofilelist) instead. I thought of asking for a pull request, but I don't think it's worth the hassle 

```
	GetProfileList(requestId := 0) {
		this.__SendRequestToObs(A_ThisFunc, requestId)
	}
```

**Comment by 5ony** [comment]
Yes, you are right again. :) I will check all functions, just to be sure.

**Comment by 5ony** [comment]
v2.0.7 is created: extra parameters removed, added missing methods.
