### ISSUE TITLE
when obs is in focus commands does not work

### ISSUE THREAD

**Issue by manjit24** [5ony/OBSWebSocketAHK#2]
command send through OBSWebSocketAHK to obs only works when obs is running in background it does not work when its in focus even if preview windows is in focus can someone tell how to make it work even when obs is in focus?

**Comment by 5ony** [comment]
I've tried it and it works for me fine, so I suppose it has to do with running privileges.

1. Make sure that the hotkey you are using in AHK is not defined as an OBS hotkey.
2. Try it running both OBS and AHK script with administrator privileges.

Let me know if these solved your issue.

**Comment by manjit24** [comment]
yes got it thank you
