### ISSUE TITLE
OBS Virtual Camera Switch OBSWebSocket 

### ISSUE THREAD

**Issue by manjit24** [5ony/OBSWebSocketAHK#4]
In there is small setting icon besides button Start Virtual camera i want a script to switch virtual camera output scene with hotkey there is two scene named Gaming and FaceCam. is it possible with OBSWebSocketAHK

**Comment by 5ony** [comment]
Short answer: it seems that OBSWebSocket (which is built in OBS) does not support this yet.

### Workaround 1, new scene collection:
- make a new Scene collection, there will be different settings for the virtual camera
- now you can use StopVirtualCam(), SetCurrentSceneCollection("other scene collection"), StartVirtualCam()
```
#NoEnv
SetBatchLines, -1
#Include lib/ObsWebSocket.ahk
class MyOBSController extends ObsWebSocket {}
obsc := new MyOBSController("ws://127.0.0.1:4455/")

F1::
	obsc.StopVirtualCam()
	obsc.SetCurrentSceneCollection("Gaming scene collection")
	Sleep, 1000
	obsc.StartVirtualCam()
return

F2::
	obsc.StopVirtualCam()
	obsc.SetCurrentSceneCollection("Facecam scene collection")
	Sleep, 1000
	obsc.StartVirtualCam()
return
```

### Workaround 2, new Virtual Camera scene:
- make a special scene for virtual camera, let's call this MyVCScene.
- set Virtual Camera Scene at virtual camera settings (output type: Scene, output selection: "MyVCScene")
- add Gaming and FaceCam scene to MyVCScene
- you can change the visibility of the included scenes under MyVCScene with AHK

### Workaround 3, automate the UI:
- using the "general" AutoHotKey you can click the mouse and use the keyboard to change the settings.

### Workaround 4, make changes in the settings file:
- close OBS, so the config is (over)written
- open %APPDATA%\OBS\basic\scenes\[yourSceneCollectionConfigName].json
- change the property: "virtual-camera":{"type":1,"scene":"yourSceneName"}
- run OBS

### Long answer

It is possible to use GetVirtualCamStatus, ToggleVirtualCam, StartVirtualCam, StopVirtualCam.
I have requested the output list with GetOutputList, and the virtual camera is there (named "virtualcam_output").
Then I've used GetOutputSettings("virtualcam_output"), but the output settings object is empty:
`{"d":{"requestId":2,"requestStatus":{"code":100,"result":true},"requestType":"GetOutputSettings","responseData":{"outputSettings":{}}},"op":7}`

I've tried to set the outputSettings with SetOutputSettings, but it does nothing. Then if I use GetOutputSettings now, it just repeats back the same object I've set with SetOutputSettings, but has no effect on anything else.

So it seems that OBSWebSocket itself does not support this feature.

**Comment by manjit24** [comment]
Got it Workaround 1 is best for me thanks man.

**Comment by 5ony** [comment]
I'm happy I could help. :)
