### ISSUE TITLE
Opening OBS with ahk hotkey 

### ISSUE THREAD

**Issue by Luxvored** [5ony/OBSWebSocketAHK#6]
Hey, I'm trying to setup a ahk to open OBS with a hotkey, would this websocket for it be able to help? Because on normal ahk I get the failed to find locale and locale/en-US.ini errors.

**Comment by 5ony** [comment]
I am afraid this is an OBS issue. My script is for controlling OBS, but it seems your OBS config files are broken/missing.

I could find some solutions for you by a quick googling, and it seems the solution is to reinstall OBS, see here:
https://obsproject.com/forum/threads/missing-locale-en-us-ini.26499/

**Comment by Luxvored** [comment]
The weird thing is that it only says that when I try to open it with AHK but when I open it normally it works just fine.

**Comment by 5ony** [comment]
One of the solutions on the forum is:
"This occurs when you run obs64.exe outside of its working directory. Use the shortcut or set the working directory manually."

You can set the working directory for AHK's Run command.

https://www.autohotkey.com/docs/v2/lib/Run.htm

**Comment by Luxvored** [comment]
That works now thanks, would it be also possible for it to open a windowed projector of a specified scene on launch?

**Comment by 5ony** [comment]
That is something which my script can help with.
The OpenSourceProjector method is the one you need:
https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md#opensourceprojector

I've found a bug in the main library, which I needed to fix, but the script below now works. Note that this does not check whether OBS is already running (I'll leave that to you), it simply establishes connection to OBS and if that is successful, opens the projector.

```
#Requires AutoHotkey >=2.0-
#Include lib/ObsWebSocket.ahk

class MyOBSController extends ObsWebSocket {
	AfterIdentified() {
		; opening a source (named "Video Capture Device") as a projector 
		this.OpenSourceProjector("Video Capture Device")
	}

	OpenSourceProjectorResponse(data) {
		MsgBox("Projector Window is opened")
	}
}

obsc := MyOBSController("ws://127.0.0.1:4455/")
F11:: MsgBox("") ; this is here only for keeping the script running
```
