### ISSUE TITLE
Is there a way to check if the websocket is connected or not?

### ISSUE THREAD

**Issue by SouDescolado** [5ony/OBSWebSocketAHK#7]
I want to bundle this with another script that I keep running on my computer, so I want to know if there is anything I can call OBSWebSocket that will return if it is connected or not

**Comment by 5ony** [comment]
There is no specific method which does this. However, I wanted to make the websocket handling better anyway, I will implement your feature request as well. Unfortunately having a bad websocket connection cannot be renewed, and it even throws errors.

I will be implementing these features quite soon. I will do inform you here when the new version is ready to be used.

**Comment by 5ony** [comment]
I have implemented the better session handling and some methods, you might need.
Check the newest version: https://github.com/5ony/OBSWebSocketAHK/tree/v2.0.3

Now you can use IsWebSocketAlive() to check whether the connection is opened (0 - not connected, 1 - connected)

```
#Requires AutoHotkey >=2.0-
#Include lib/ObsWebSocket.ahk

obsc := ObsWebSocket("ws://127.0.0.1:4455/")
Sleep(2000)
msgBox(obsc.IsWebSocketAlive())
```

Let me know, if you had success.

**Comment by SouDescolado** [comment]
I am using an [Interception and AHK method](https://github.com/evilC/AutoHotInterception) to change all the keys to a combo of F13 to F24, so it doesn't mess with my regular keyboard or gameplay. However at OBS you cannot use a hotkey with two+ keys that doesn't involv a CTRL, a SHIFT and/or an ALT.

With this new thing, I just mapped to, when I press the specific keys that I want for change, it checks if the websocket is on, and, if not, it retries the reconnection.
I manually remove the Tray Alerts here, so no problems on my side, but it would be nice to have a "Silent" option

Anyways, here is a snippet of my code:
```
	else if (code = "16"||code = "17"||code = "18"||code = "19"||code = "20") ;The keys Q W E R T on my secondary keyboard
		{
			if (obsc.IsWebSocketAlive() = 0)
			{
				obsc.RetryConnection()
			}
```

Maybe I'll also check if OBS process exists, just in case. But it works fine now, so thanks!

**Comment by 5ony** [comment]
> it would be nice to have a "Silent" option

You are right, it is a bit annoying. I've added SetSilentMode() to enable/disable tray tips, default is off, so you do not even have to call this function. You can find this in the newest code [v2.0.4](https://github.com/5ony/OBSWebSocketAHK/tree/v2.0.4)
